# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.4
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

      # run build
      - run:
          name: Build files in the dist folder
          command: npm run build

      # cache dist for use in deploy job
      - save_cache:
          key: v1-dist-{{.Environment.CIRCLE_BRANCH}}-{{.Environment.CIRCLE_SHA1}}
          paths:
            - dist

  deploy:
    docker:
      - image: circleci/node:8.9.4
      
    working_directory: ~/repo

    steps:
      # restore dist from the build job
      - restore_cache:
          key: v1-dist-{{.Environment.CIRCLE_BRANCH}}-{{.Environment.CIRCLE_SHA1}}
      
      # install aws cli
      - run:
          name: Install aws cli for use in deploying to s3 bucket
          command: sudo apt-get -y -qq install awscli
      
      # deploy to s3 bucket
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws --region ap-southeast-1 s3 sync dist $AWS_S3_BUCKET --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master